name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: "18.x"
        registry-url: "https://registry.npmjs.org"

    - name: Install dependencies
      run: |
        yarn install --cwd example --frozen-lockfile
        yarn install --frozen-lockfile
      shell: bash
