export enum SignalOperator {
  GREATER_THAN = 'GREATER_THAN',
  LESS_THAN = 'LESS_THAN',
  EQUAL_TO = 'EQUAL_TO',
  CROSSES = 'CROSSES',
  CROSSES_ABOVE = 'CROSSES_ABOVE',
  CROSSES_BELOW = 'CROSSES_BELOW',
  TURNS_UP = 'TURNS_UP',
  TURNS_DOWN = 'TURNS_DOWN',
  INCREASES = 'INCREASES',
  DECREASES = 'DECREASES',
  DOES_NOT_CHANGE = 'DOES_NOT_CHANGE',
}
