export const ChartIQLanguages = {
  EN: { title: 'English', code: 'en-US' },
  DE: { title: 'German', code: 'de-DE' },
  FR: { title: 'French', code: 'fr-FR' },
  RU: { title: 'Russian', code: 'ru-RU' },
  IT: { title: 'Italian', code: 'it-IT' },
  ES: { title: 'Spanish', code: 'es-ES' },
  PT: { title: 'Portuguese', code: 'pt-PT' },
  HU: { title: 'Hungarian', code: 'hu-HU' },
  ZH: { title: 'Chinese', code: 'zh-CN' },
  JA: { title: 'Japanese', code: 'ja-JP' },
  AR: { title: 'Arabic', code: 'ar-EG' },
};

const enTranslationAsKeys = [
  '%D',
  '%D Moving Average Type',
  '%D Periods',
  '%K',
  '%K Double Smoothing Periods',
  '%K Periods',
  '%K Smoothing Periods',
  '%b',
  '(Scroll for more options)',
  '(UTC) Casablanca',
  '(UTC) Dublin',
  '(UTC+02:00) Cairo',
  '(UTC+02:00) Cyprus',
  '(UTC+02:00) Jerusalem',
  '(UTC+02:00) Kaliningrad',
  '(UTC+03:00) Istanbul',
  '(UTC+03:00) Nairobi',
  '(UTC+03:00) Simferopol',
  '(UTC+03:30) Tehran',
  '(UTC+04:00) Baku',
  '(UTC+04:30) Kabul',
  '(UTC+05:00) Yekaterinburg',
  '(UTC+05:45) Kathmandu',
  '(UTC+06:00) Almaty',
  '(UTC+06:00) Omsk',
  '(UTC+06:30) Yangon',
  '(UTC+07:00) Hovd',
  '(UTC+07:00) Krasnoyarsk',
  '(UTC+07:00) Novokuznetsk',
  '(UTC+08:00) Irkutsk',
  '(UTC+08:00) Perth',
  '(UTC+08:45) Eucla',
  '(UTC+09:00) Pyongyang',
  '(UTC+09:00) Seoul',
  '(UTC+09:30) Adelaide',
  '(UTC+09:30) Darwin',
  '(UTC+10:00) Brisbane',
  '(UTC+11:00) Magadan',
  '(UTC+12:45) Chatham',
  '(UTC+13:00) Samoa',
  '(UTC+13:00) Tonga',
  '(UTC+14:00) Kiritimati',
  '(UTC-01:00) Azores',
  '(UTC-01:00) Cape Verde Islands',
  '(UTC-02:00) Mid-Atlantic',
  '(UTC-03:00) Buenos Aires',
  '(UTC-03:00) Montevideo',
  '(UTC-03:00) Punta Arenas',
  '(UTC-03:00) Sao Paulo',
  '(UTC-03:30) Newfoundland and Labrador',
  '(UTC-04:00) Asuncion',
  '(UTC-04:00) Atlantic Time (Canada)',
  '(UTC-04:00) Caracas',
  '(UTC-04:00) Santiago',
  '(UTC-05:00) Eastern Time (US and Canada)',
  '(UTC-05:00) Indiana (East)',
  '(UTC-06:00) Central America',
  '(UTC-06:00) Central Time (US and Canada)',
  '(UTC-06:00) Saskatchewan',
  '(UTC-07:00) Arizona',
  '(UTC-07:00) Mountain Time (US and Canada)',
  '(UTC-08:00) Pacific Time (US and Canada)',
  '(UTC-08:00) Tijuana',
  '(UTC-09:00) Alaska',
  '(UTC-10:00) Hawaii',
  '+DI',
  '+VI',
  '-DI',
  '-VI',
  '1 D',
  '1 Hour',
  '1 Min',
  '1 Mo',
  '1 Standard Deviation (1σ)',
  '1 W',
  '10 Min',
  '10m',
  '13px',
  '15 Min',
  '15m',
  '1D',
  '1H',
  '1M',
  '1W',
  '1Y',
  '1m',
  '2 Standard Deviation (1σ)',
  '2 Standard Deviation (2σ)',
  '3 Standard Deviation (1σ)',
  '3 Standard Deviation (3σ)',
  '30 Min',
  '30m',
  '3M',
  '4 Hour',
  '4H',
  '5 Min',
  '5D',
  '5Y',
  '5m',
  '6M',
  'ADD',
  'ADX',
  'ADX/DMS',
  'ALL',
  'ATH Lookback Period',
  'ATR',
  'ATR Bands',
  'ATR Bands Bottom',
  'ATR Bands Channel',
  'ATR Bands Top',
  'ATR Trailing Stop',
  'ATR Trailing Stops',
  'Abstract',
  'Acc Swing',
  'Accumulation/Distribution',
  'Accumulative Swing Index',
  'Add',
  'Add Stop Loss',
  'Add Take Profit',
  'All-Time High Lookback Period',
  'Alligator',
  'Annotation',
  'Arc',
  'Aroon',
  'Aroon Down',
  'Aroon Osc',
  'Aroon Oscillator',
  'Aroon Up',
  'Arrow',
  'Auto Select',
  'Average',
  'Average Line',
  'Average True Range',
  'Average Type',
  'Awesome',
  'Awesome Oscillator',
  'Axis Label',
  'Axis Label:',
  'Axis Text',
  'B',
  'BATS BZX real-time.',
  'Background',
  'Background Color',
  'Balance of Power',
  'Bandwidth',
  'Bar',
  'Bars',
  'Bars Color',
  'Base Line',
  'Base Line Period',
  'Baseline',
  'Baseline Delta',
  'Bearish',
  'Beta',
  'Beta Callouts Candle Border',
  'Black',
  'Boll %b',
  'Boll BW',
  'Bollinger %b',
  'Bollinger Bands',
  'Bollinger Bands Bottom',
  'Bollinger Bands Median',
  'Bollinger Bands Top',
  'Bollinger Bandwidth',
  'Border',
  'Bulge Threshold',
  'Bullish',
  'Buy Stops',
  'COMMODITIES',
  'CURRENCIES',
  'Callout',
  'Callouts',
  'Candle',
  'Candle Border',
  'Candle Borders',
  'Candle Color',
  'Candle Wick',
  'Candles',
  'Center Of Gravity',
  'Chaikin MF',
  'Chaikin Money Flow',
  'Chaikin Vol',
  'Chaikin Volatility',
  'Chande Fcst',
  'Chande Forecast Oscillator',
  'Chande Momentum Oscillator',
  'Chande Mtm',
  'Change Timezone',
  'Channel',
  'Channel Fill',
  'Chart',
  'Chart Preferences',
  'Chart Scale',
  'Chart Shared Successfully!',
  'Chart Style',
  'Chart Type',
  'Check',
  'Choose Timezone',
  'Choose language',
  'Choppiness Index',
  'Clear',
  'Clear All',
  'Clear All Drawings',
  'Close',
  'Color',
  'Colored Bar',
  'Colored Line',
  'Commodity Channel Index',
  'Compare',
  'Comparison Symbol',
  'Composite',
  'Composite RSI',
  'Continuous',
  'Conversion Line',
  'Conversion Line Period',
  'Coppock',
  'Coppock Curve',
  'Correl',
  'Correlation',
  'Correlation Coefficient',
  'Courier',
  'Create',
  'Create Custom Theme',
  'Create Image',
  'Create a New Custom Theme',
  'Cross',
  'Crosshair',
  'Crosshairs',
  'Crossline',
  'Current Studies',
  'Current Symbols',
  'Current Timezone is',
  'Custom Themes',
  'Cycle 1',
  'Cycle 2',
  'Cycle 3',
  'D',
  'Darvas',
  'Darvas Box',
  'Data delayed 15 min.',
  'Data is randomized.',
  'Data is real-time.',
  'Date Dividers',
  'Date/Time',
  'Date/Time:',
  'Day',
  'Days Per Year',
  'Decreasing Bar',
  'Default',
  'Default Themes',
  'Delete',
  'Delete Study',
  'Demo data.',
  'Detrended',
  'Detrended Price Oscillator',
  'Directional',
  'Disparity Index',
  'Display',
  'Display 1 Standard Deviation (1σ)',
  'Display 2 Standard Deviation (2σ)',
  'Display 3 Standard Deviation (3σ)',
  'Display Average',
  'Distance(%)',
  'Divergence',
  "Don't see your study below? Type in your search here.",
  'Donchian Channel',
  'Donchian High',
  'Donchian Low',
  'Donchian Median',
  'Donchian Width',
  'Done',
  'Doodle',
  'Double Exponential',
  'Double Smoothing Period',
  'Down Volume',
  'Downtrend',
  'Draw',
  'EF',
  'EF Trigger',
  'Ease of Movement',
  'Edit',
  'Edit Settings...',
  'Ehler Fisher',
  'Ehler Fisher Transform',
  'Elder Bear Power',
  'Elder Bull Power',
  'Elder Force',
  'Elder Force Index',
  'Elder Impulse System',
  'Elder Ray Index',
  'Ellipse',
  'End of day data.',
  'Enter Symbol',
  'Enter name of view:',
  'Events',
  'Exit Field',
  'Exponential',
  'Extended Hours',
  'FOREX',
  'FUNDS',
  'FUTURES',
  'FX',
  'Fade',
  'Fake',
  'Fan',
  'Fast',
  'Fast MA Period',
  'Fib Arc',
  'Fib Fan',
  'Fib Time Zone',
  'Fibonacci',
  'Field',
  'Fill',
  'Focus Arrow',
  'Forecast',
  'Formula courtesy',
  'Fractal Channel',
  'Fractal Chaos',
  'Fractal Chaos Bands',
  'Fractal Chaos Oscillator',
  'Fractal High',
  'Fractal Low',
  'Gain',
  'Gann Fan',
  'Garamond',
  'Gartley',
  'Gator',
  'Gator Oscillator',
  'Generating Image',
  'Ghost',
  'Ghost Boxes',
  'Gopala',
  'Gopalakrishnan Range Index',
  'Gradient',
  'Green',
  'Grid Lines',
  'H',
  'HHV/LLV Lookback',
  'Heart',
  'Heaviest Rate of Change Period',
  'Heaviest SMA Period',
  'Heavy Rate of Change Period',
  'Heavy SMA Period',
  'Heikin Ashi',
  'Heikin-Ashi',
  'Helvetica',
  'High',
  'High Low',
  'High Low Bands',
  'High Low Bottom',
  'High Low Median',
  'High Low Top',
  'High Minus Low',
  'High Period',
  'High-Low',
  'HighLow',
  'Highest High Value',
  'Hist Vol',
  'Histogram',
  'Historical Volatility',
  'Hollow Candle',
  'Horizontal',
  'Hull',
  'I',
  'INDEXES',
  'INDICES',
  'Ichimoku Clouds',
  'Increasing Bar',
  'Index',
  'Info',
  'Intercept',
  'Interval',
  'Intraday Momentum Index',
  'Intraday Mtm',
  'Jaw',
  'Jaw Offset',
  'Jaw Period',
  'KST',
  'KSTSignal',
  'Kagi',
  'Keltner',
  'Keltner Bottom',
  'Keltner Channel',
  'Keltner Median',
  'Keltner Top',
  'Klinger',
  'Klinger Volume Oscillator',
  'KlingerSignal',
  'LR Slope',
  'Lagging Span',
  'Lagging Span Period',
  'Leading Span A',
  'Leading Span B',
  'Leading Span B Period',
  'Level Offset',
  'Levels',
  'Light Rate of Change Period',
  'Light SMA Period',
  'Lightest Rate of Change Period',
  'Lightest SMA Period',
  'Limit Move Value',
  'Lin Fcst',
  'Lin Incpt',
  'Lin R2',
  'Line',
  'Line Break',
  'Line/Bar Chart',
  'Linear Reg Forecast',
  'Linear Reg Intercept',
  'Linear Reg R2',
  'Linear Reg Slope',
  'Lips',
  'Lips Offset',
  'Lips Period',
  'Locale',
  'Log Scale',
  'Long Cycle',
  'Long RoC',
  'Loss',
  'Low',
  'Low Period',
  'Lowest Low Value',
  'M',
  'M Flow',
  'MA',
  'MA Env',
  'MA Env Bottom',
  'MA Env Median',
  'MA Env Top',
  'MA Period',
  'MACD',
  'Market Data',
  'Market Facilitation Index',
  'Mass Idx',
  'Mass Index',
  'Maximum AF',
  'Measure',
  'Med Price',
  'Median Price',
  'Min Tick Value',
  'Minimum AF',
  'Momentum',
  'Momentum Indicator',
  'Money Flow Index',
  'More',
  'More studies',
  'Mountain',
  'Mountain Charts',
  'Mountain Color',
  'Moving Average',
  'Moving Average Deviation',
  'Moving Average Envelope',
  'Moving Average Type',
  'Multiplier',
  'Name',
  'Neg Vol',
  'Negative Bar',
  'Negative Volume Index',
  'Neutral',
  'New Custom Theme',
  'New Theme',
  'New Theme Name',
  'New Theme Name:',
  'Night',
  'None',
  'None available',
  'Not enough data to compute',
  'Offset',
  'On Bal Vol',
  'On Balance Volume',
  'Open',
  'Open shared chart in new window',
  'OverBought',
  'OverSold',
  'Overlay',
  'P Rel',
  'PMO',
  'PMOSignal',
  'Palatino',
  'Parabolic SAR',
  'Percent',
  'Perf Idx',
  'Performance Index',
  'Period',
  'Pitchfork',
  'Pivot',
  'Pivot Points',
  'Plot Type',
  'Plots',
  'Point & Figure',
  'Points',
  'Points Or Percent',
  'Popular Studies',
  'Pos Vol',
  'Positive Bar',
  'Positive Volume Index',
  'Pretty Good',
  'Pretty Good Oscillator',
  'Price',
  'Price Minimum',
  'Price Momentum Oscillator',
  'Price Osc',
  'Price Oscillator',
  'Price ROC',
  'Price Rate of Change',
  'Price Relative',
  'Price Vol',
  'Price Volume Trend',
  'Prime Bands Bottom',
  'Prime Bands Channel',
  'Prime Bands Top',
  'Prime Number',
  'Prime Number Bands',
  'Prime Number Oscillator',
  "Pring's Know Sure Thing",
  "Pring's Special K",
  'Psychological Line',
  'QStick',
  'Quadrant Lines',
  'RAVI',
  'RSI',
  'RSquared',
  'Rainbow Moving Average',
  'Rainbow Oscillator',
  'Random Walk',
  'Random Walk High',
  'Random Walk Index',
  'Random Walk Low',
  'Range Bars',
  'Range Selector',
  'Rate Of Change',
  'Ray',
  'Rectangle',
  'Redo',
  'Regression Line',
  'Rel Vig',
  'Rel Vol',
  'RelVigSignal',
  'Relative Vigor Index',
  'Relative Volatility',
  'Renko',
  'Resistance 1',
  'Resistance 2',
  'Resistance 3',
  'Result',
  'Retracement',
  'Risk/Reward',
  'SMA1',
  'SMA10',
  'SMA2',
  'SMA3',
  'SMA4',
  'SMA5',
  'SMA6',
  'SMA7',
  'SMA8',
  'SMA9',
  'STARC Bands',
  'STARC Bands Bottom',
  'STARC Bands Median',
  'STARC Bands Top',
  'STD Dev',
  'STD Period',
  'STOCKS',
  'Save',
  'Save Theme',
  'Save View',
  'Saved View',
  'Saved Views',
  'Scale Factor',
  'Schaff',
  'Schaff Trend Cycle',
  'Search',
  'Segment',
  'Select Tool',
  'Sell Stops',
  'Series',
  'Set Point & Figure Parameters',
  'Set Price Lines',
  'Set Range',
  'Set Reversal Percentage',
  'Settings',
  'Shading',
  'Shape',
  'Shape - Arrow',
  'Shape - Check',
  'Shape - Cross',
  'Shape - Focus',
  'Shape - Heart',
  'Shape - Star',
  'Share',
  'Share This Chart',
  'Share Your Chart',
  'Shift',
  'Shift Percentage',
  'Shift Type',
  'Shinohara Intensity Ratio',
  'Short Cycle',
  'Short RoC',
  'Show All',
  'Show Fractals',
  'Show Zones',
  'Signal',
  'Signal Period',
  'Signal Periods',
  'Simple',
  'Simple Circle',
  'Simple Square',
  'Simulated data.',
  'Slope',
  'Slow',
  'Slow MA Period',
  'Smooth',
  'Smoothing Period',
  'Speed Resistance Arc',
  'Speed Resistance Line',
  'Squarewave',
  'Squat',
  'Standard Deviation',
  'Standard Deviations',
  'Star',
  'Stch Mtm',
  'Stochastic Momentum Index',
  'Stochastics',
  'Stop Levels',
  'Stop Loss',
  'Stops',
  'Strong Ratio',
  'Studies',
  'Study',
  'Supertrend',
  'Support 1',
  'Support 2',
  'Support 3',
  'Swing',
  'Swing Index',
  'Symbol',
  'T',
  'TII',
  'TRIX',
  'Take Profit',
  'Teeth',
  'Teeth Offset',
  'Teeth Period',
  'Themes',
  'This is a callout marker',
  'Time Cycle',
  'Time Fcst',
  'Time Series',
  'Time Series Forecast',
  'Time Zone',
  'Times New Roman',
  'Timezone',
  'Tirone Levels',
  'To set your timezone use the location button below or scroll through the following list',
  'Tolerance Percentage',
  'Trade Vol',
  'Trade Volume Index',
  'Trend Intensity Index',
  'Triangular',
  'Triple Exponential',
  'True Range',
  'Twiggs',
  'Twiggs Money Flow',
  'Type',
  'Typical Price',
  'Ulcer Index',
  'Ultimate',
  'Ultimate Oscillator',
  'Underlay',
  'Undo',
  'Units',
  'Unrealized Gain/Loss',
  'Up Volume',
  'Uploading Image',
  'Uptrend',
  'Use My Current Location',
  'Use Volume',
  'Use the following link to share your chart:',
  'VIDYA',
  'VT HZ Filter',
  'VWAP',
  'Valuation Lines',
  'Variable',
  'Vchart',
  'Vertical',
  'Vertical Horizontal Filter',
  'Views',
  'Vol',
  'Vol Osc',
  'Vol ROC',
  'Volume',
  'Volume % of Avg',
  'Volume Candle',
  'Volume Chart',
  'Volume Not Available',
  'Volume Oscillator',
  'Volume Profile',
  'Volume Rate of Change',
  'Volume Spike',
  'Volume Underlay',
  'Vortex Indicator',
  'W',
  'W Acc Dist',
  'Weak Ratio',
  'Weighted',
  'Weighted Close',
  'Welles Wilder',
  'White',
  'Williams %R',
  'YTD',
  'Your timezone is your current location',
  'ZigZag',
  'by Xignite.',
  'cancel',
  'close',
  'daily',
  'ema',
  'fibonacci',
  'field',
  'harmonic',
  'high/low',
  'ma',
  'mean',
  'median',
  'ms',
  'or',
  'percent',
  'pips',
  'points',
  'right-click to delete',
  'right-click to manage',
  's',
  'save',
  'squarewave',
  'standard',
  'vdma',
  'vol profile',
  'vol undr',
  'weekly',
];

export const defaultENTranslationsMap: Record<string, string> = enTranslationAsKeys.reduce(
  (acc, key) => ({
    ...acc,
    [key]: key,
  }),
  {},
);

export const defaultENTranslations = {
  cancel: 'Cancel',
  close: 'Close',
  Search: 'Search',
  ALL: 'ALL',
  FX: 'FX',
  'Chart Style': 'Chart Style',
  'Chart Type': 'Chart Type',
  Open: 'Open',
  High: 'High',
  Low: 'Low',
  Close: 'Close',
  Volume: 'Volume',
  Price: 'Price',
  Apply: 'Apply',
  Add: 'Add',
  Save: 'Save',
  'Chart Preferences': 'Chart Preferences',
  'Log Scale': 'Log Scale',
  'Extended Hours': 'Extended Hours',
  Settings: 'Settings',
  'Choose language': 'Choose language',
  Delete: 'Delete',
};
